package com.zhongyang.java.pojo;

import java.io.Serializable;
import java.util.Date;

import com.zhongyang.java.vo.employee.EmployeeStatus;

public class Employee implements Serializable{
    
    private String id;

    private String clientcode;

    private String empId;

    private Boolean enabled;

    private String idnumber;

    private Date lastlogindate;
    
    private String loginName;

    private String mobile;

    private String name;

    private Boolean needchangepassword;

    private String passphrase;

    private Date registerdate;
    
    private String salt;

    private String branchId;

    private String regDate;
    
    private String lastDate;
    
    private String orgId;
    
    private String jobId;
    
    private EmployeeStatus statu;
    
    private String orgName;
     
    public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getJobId() {
		return jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	public EmployeeStatus getStatu() {
		return statu;
	}

	public void setStatu(EmployeeStatus statu) {
		this.statu = statu;
	}

	public String getRegDate() {
		return regDate;
	}

	public void setRegDate(String regDate) {
		this.regDate = regDate;
	}

	public String getLastDate() {
		return lastDate;
	}

	public void setLastDate(String lastDate) {
		this.lastDate = lastDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.ID
     *
     * @return the value of TB_EMPLOYEE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.ID
     *
     * @param id the value for TB_EMPLOYEE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.ClientCode
     *
     * @return the value of TB_EMPLOYEE.ClientCode
     *
     * @mbggenerated
     */
    public String getClientcode() {
        return clientcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.ClientCode
     *
     * @param clientcode the value for TB_EMPLOYEE.ClientCode
     *
     * @mbggenerated
     */
    public void setClientcode(String clientcode) {
        this.clientcode = clientcode == null ? null : clientcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.EMP_ID
     *
     * @return the value of TB_EMPLOYEE.EMP_ID
     *
     * @mbggenerated
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.EMP_ID
     *
     * @param empId the value for TB_EMPLOYEE.EMP_ID
     *
     * @mbggenerated
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.ENABLED
     *
     * @return the value of TB_EMPLOYEE.ENABLED
     *
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.ENABLED
     *
     * @param enabled the value for TB_EMPLOYEE.ENABLED
     *
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.IDNUMBER
     *
     * @return the value of TB_EMPLOYEE.IDNUMBER
     *
     * @mbggenerated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.IDNUMBER
     *
     * @param idnumber the value for TB_EMPLOYEE.IDNUMBER
     *
     * @mbggenerated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.LASTLOGINDATE
     *
     * @return the value of TB_EMPLOYEE.LASTLOGINDATE
     *
     * @mbggenerated
     */
    public Date getLastlogindate() {
        return lastlogindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.LASTLOGINDATE
     *
     * @param lastlogindate the value for TB_EMPLOYEE.LASTLOGINDATE
     *
     * @mbggenerated
     */
    public void setLastlogindate(Date lastlogindate) {
        this.lastlogindate = lastlogindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.LOGIN_NAME
     *
     * @return the value of TB_EMPLOYEE.LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.LOGIN_NAME
     *
     * @param loginName the value for TB_EMPLOYEE.LOGIN_NAME
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.MOBILE
     *
     * @return the value of TB_EMPLOYEE.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.MOBILE
     *
     * @param mobile the value for TB_EMPLOYEE.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.NAME
     *
     * @return the value of TB_EMPLOYEE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.NAME
     *
     * @param name the value for TB_EMPLOYEE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.NEEDCHANGEPASSWORD
     *
     * @return the value of TB_EMPLOYEE.NEEDCHANGEPASSWORD
     *
     * @mbggenerated
     */
    public Boolean getNeedchangepassword() {
        return needchangepassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.NEEDCHANGEPASSWORD
     *
     * @param needchangepassword the value for TB_EMPLOYEE.NEEDCHANGEPASSWORD
     *
     * @mbggenerated
     */
    public void setNeedchangepassword(Boolean needchangepassword) {
        this.needchangepassword = needchangepassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.PASSPHRASE
     *
     * @return the value of TB_EMPLOYEE.PASSPHRASE
     *
     * @mbggenerated
     */
    public String getPassphrase() {
        return passphrase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.PASSPHRASE
     *
     * @param passphrase the value for TB_EMPLOYEE.PASSPHRASE
     *
     * @mbggenerated
     */
    public void setPassphrase(String passphrase) {
        this.passphrase = passphrase == null ? null : passphrase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.REGISTERDATE
     *
     * @return the value of TB_EMPLOYEE.REGISTERDATE
     *
     * @mbggenerated
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.REGISTERDATE
     *
     * @param registerdate the value for TB_EMPLOYEE.REGISTERDATE
     *
     * @mbggenerated
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.SALT
     *
     * @return the value of TB_EMPLOYEE.SALT
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.SALT
     *
     * @param salt the value for TB_EMPLOYEE.SALT
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_EMPLOYEE.BRANCH_ID
     *
     * @return the value of TB_EMPLOYEE.BRANCH_ID
     *
     * @mbggenerated
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_EMPLOYEE.BRANCH_ID
     *
     * @param branchId the value for TB_EMPLOYEE.BRANCH_ID
     *
     * @mbggenerated
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }
}