package com.zhongyang.java.pojo;

import java.io.Serializable;

public class EmpRoleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为RF_EMP_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为RF_EMP_ROLE.EMP_ID
     *
     * @mbggenerated
     */
    private String empId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RF_EMP_ROLE.ROLE_ID
     *
     * @return the value of RF_EMP_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RF_EMP_ROLE.ROLE_ID
     *
     * @param roleId the value for RF_EMP_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RF_EMP_ROLE.EMP_ID
     *
     * @return the value of RF_EMP_ROLE.EMP_ID
     *
     * @mbggenerated
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RF_EMP_ROLE.EMP_ID
     *
     * @param empId the value for RF_EMP_ROLE.EMP_ID
     *
     * @mbggenerated
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }
}