package com.zhongyang.java.pojo;

public class SysAuthorities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_AUTHORITIES.privilige
     *
     * @mbggenerated
     */
    private String privilige;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_AUTHORITIES.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_AUTHORITIES.pindex
     *
     * @mbggenerated
     */
    
    private String cato;
    
    
    public String getCato() {
		return cato;
	}

	public void setCato(String cato) {
		this.cato = cato;
	}

	private Integer pindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_AUTHORITIES.type
     *
     * @mbggenerated
     */
    private String type;
    
    private boolean flag;

    public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTHORITIES.privilige
     *
     * @return the value of TB_AUTHORITIES.privilige
     *
     * @mbggenerated
     */
    public String getPrivilige() {
        return privilige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTHORITIES.privilige
     *
     * @param privilige the value for TB_AUTHORITIES.privilige
     *
     * @mbggenerated
     */
    public void setPrivilige(String privilige) {
        this.privilige = privilige == null ? null : privilige.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTHORITIES.name
     *
     * @return the value of TB_AUTHORITIES.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTHORITIES.name
     *
     * @param name the value for TB_AUTHORITIES.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTHORITIES.pindex
     *
     * @return the value of TB_AUTHORITIES.pindex
     *
     * @mbggenerated
     */
    public Integer getPindex() {
        return pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTHORITIES.pindex
     *
     * @param pindex the value for TB_AUTHORITIES.pindex
     *
     * @mbggenerated
     */
    public void setPindex(Integer pindex) {
        this.pindex = pindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTHORITIES.type
     *
     * @return the value of TB_AUTHORITIES.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTHORITIES.type
     *
     * @param type the value for TB_AUTHORITIES.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}