package com.zhongyang.java.pojo;

import java.io.Serializable;
import java.util.Date;

public class SysFuncList implements Serializable {
	
	private Integer indexKey;
	private String privilige;
	private String hclass;
	

	public Integer getIndexKey() {
		return indexKey;
	}

	public void setIndexKey(Integer indexKey) {
		this.indexKey = indexKey;
	}

	public String getPrivilige() {
		return privilige;
	}

	public void setPrivilige(String privilige) {
		this.privilige = privilige;
	}

	public String getHclass() {
		return hclass;
	}

	public void setHclass(String hclass) {
		this.hclass = hclass;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.func_url
     *
     * @mbggenerated
     */
    private String funcUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.func_name
     *
     * @mbggenerated
     */
    private String funcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.is_del
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.create_id
     *
     * @mbggenerated
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.modify_id
     *
     * @mbggenerated
     */
    private Integer modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 1为菜单，0为按钮,所属表字段为TB_SYS_FUNC_LIST.is_menu
     *
     * @mbggenerated
     */
    private Integer isMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.fuc_level
     *
     * @mbggenerated
     */
    private Integer fucLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.LEVEL_FUNC
     *
     * @mbggenerated
     */
    private Integer levelFunc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.description_t
     *
     * @mbggenerated
     */
    private String descriptionT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ,所属表字段为TB_SYS_FUNC_LIST.ICO_CLASS
     *
     * @mbggenerated
     */
    private String icoClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.id
     *
     * @return the value of TB_SYS_FUNC_LIST.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.id
     *
     * @param id the value for TB_SYS_FUNC_LIST.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.func_url
     *
     * @return the value of TB_SYS_FUNC_LIST.func_url
     *
     * @mbggenerated
     */
    public String getFuncUrl() {
        return funcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.func_url
     *
     * @param funcUrl the value for TB_SYS_FUNC_LIST.func_url
     *
     * @mbggenerated
     */
    public void setFuncUrl(String funcUrl) {
        this.funcUrl = funcUrl == null ? null : funcUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.func_name
     *
     * @return the value of TB_SYS_FUNC_LIST.func_name
     *
     * @mbggenerated
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.func_name
     *
     * @param funcName the value for TB_SYS_FUNC_LIST.func_name
     *
     * @mbggenerated
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.parent_id
     *
     * @return the value of TB_SYS_FUNC_LIST.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.parent_id
     *
     * @param parentId the value for TB_SYS_FUNC_LIST.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.sort
     *
     * @return the value of TB_SYS_FUNC_LIST.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.sort
     *
     * @param sort the value for TB_SYS_FUNC_LIST.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.description
     *
     * @return the value of TB_SYS_FUNC_LIST.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.description
     *
     * @param description the value for TB_SYS_FUNC_LIST.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.status
     *
     * @return the value of TB_SYS_FUNC_LIST.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.status
     *
     * @param status the value for TB_SYS_FUNC_LIST.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.is_del
     *
     * @return the value of TB_SYS_FUNC_LIST.is_del
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.is_del
     *
     * @param isDel the value for TB_SYS_FUNC_LIST.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.create_id
     *
     * @return the value of TB_SYS_FUNC_LIST.create_id
     *
     * @mbggenerated
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.create_id
     *
     * @param createId the value for TB_SYS_FUNC_LIST.create_id
     *
     * @mbggenerated
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.modify_id
     *
     * @return the value of TB_SYS_FUNC_LIST.modify_id
     *
     * @mbggenerated
     */
    public Integer getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.modify_id
     *
     * @param modifyId the value for TB_SYS_FUNC_LIST.modify_id
     *
     * @mbggenerated
     */
    public void setModifyId(Integer modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.create_time
     *
     * @return the value of TB_SYS_FUNC_LIST.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.create_time
     *
     * @param createTime the value for TB_SYS_FUNC_LIST.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.modify_date
     *
     * @return the value of TB_SYS_FUNC_LIST.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.modify_date
     *
     * @param modifyDate the value for TB_SYS_FUNC_LIST.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.is_menu
     *
     * @return the value of TB_SYS_FUNC_LIST.is_menu
     *
     * @mbggenerated
     */
    public Integer getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.is_menu
     *
     * @param isMenu the value for TB_SYS_FUNC_LIST.is_menu
     *
     * @mbggenerated
     */
    public void setIsMenu(Integer isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.fuc_level
     *
     * @return the value of TB_SYS_FUNC_LIST.fuc_level
     *
     * @mbggenerated
     */
    public Integer getFucLevel() {
        return fucLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.fuc_level
     *
     * @param fucLevel the value for TB_SYS_FUNC_LIST.fuc_level
     *
     * @mbggenerated
     */
    public void setFucLevel(Integer fucLevel) {
        this.fucLevel = fucLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.LEVEL_FUNC
     *
     * @return the value of TB_SYS_FUNC_LIST.LEVEL_FUNC
     *
     * @mbggenerated
     */
    public Integer getLevelFunc() {
        return levelFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.LEVEL_FUNC
     *
     * @param levelFunc the value for TB_SYS_FUNC_LIST.LEVEL_FUNC
     *
     * @mbggenerated
     */
    public void setLevelFunc(Integer levelFunc) {
        this.levelFunc = levelFunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.description_t
     *
     * @return the value of TB_SYS_FUNC_LIST.description_t
     *
     * @mbggenerated
     */
    public String getDescriptionT() {
        return descriptionT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.description_t
     *
     * @param descriptionT the value for TB_SYS_FUNC_LIST.description_t
     *
     * @mbggenerated
     */
    public void setDescriptionT(String descriptionT) {
        this.descriptionT = descriptionT == null ? null : descriptionT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.TYPE
     *
     * @return the value of TB_SYS_FUNC_LIST.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.TYPE
     *
     * @param type the value for TB_SYS_FUNC_LIST.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SYS_FUNC_LIST.ICO_CLASS
     *
     * @return the value of TB_SYS_FUNC_LIST.ICO_CLASS
     *
     * @mbggenerated
     */
    public String getIcoClass() {
        return icoClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SYS_FUNC_LIST.ICO_CLASS
     *
     * @param icoClass the value for TB_SYS_FUNC_LIST.ICO_CLASS
     *
     * @mbggenerated
     */
    public void setIcoClass(String icoClass) {
        this.icoClass = icoClass == null ? null : icoClass.trim();
    }
}