package com.zhongyang.java.dao;

import java.util.List;

import com.zhongyang.java.pojo.Employee;
import com.zhongyang.java.pojo.Role;
import com.zhongyang.java.system.page.Page;

public interface EmployeeMapper {
	
	Employee selectByLoginName(String loginName);
	
	Employee selectByCell(String mobile);
	
	List<Employee> selectAll(Page<Employee> page);
	
	List<Employee> selectByRole(Role role);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_EMPLOYEE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_EMPLOYEE
     *
     * @mbggenerated
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_EMPLOYEE
     *
     * @mbggenerated
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_EMPLOYEE
     *
     * @mbggenerated
     */
    Employee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_EMPLOYEE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_EMPLOYEE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Employee record);
    
    public Employee selectByParams(Employee emp);
}