package com.zhongyang.java.dao;

import java.util.List;

import com.zhongyang.java.pojo.EmpRoleKey;

public interface EmpRoleMapper {
	
	EmpRoleKey selectEmpRoleKey(EmpRoleKey er);
	
	EmpRoleKey getUserRole(String userId);
	
	List<EmpRoleKey> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RF_EMP_ROLE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(EmpRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RF_EMP_ROLE
     *
     * @mbggenerated
     */
    int insert(EmpRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RF_EMP_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(EmpRoleKey record);
}