package com.zhongyang.java.dao;

import java.util.List;
import java.util.Map;

import com.zhongyang.java.pojo.Role;

public interface RoleMapper {
	
	List<Role> selectUserAuth(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ROLE
     *
     * @mbggenerated
     */
	
	
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ROLE
     *
     * @mbggenerated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ROLE
     *
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ROLE
     *
     * @mbggenerated
     */
    Role selectByPrimaryKey(String id);
    
    List<Role> selectAll();
    
    Role selectByName(Role role);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ROLE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Role record);
}