package com.zhongyang.java.dao;

import java.util.List;

import com.zhongyang.java.pojo.SysAuthorities;

public interface SysAuthoritiesMapper {
	
	List<SysAuthorities> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTHORITIES
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String privilige);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTHORITIES
     *
     * @mbggenerated
     */
    int insert(SysAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTHORITIES
     *
     * @mbggenerated
     */
    int insertSelective(SysAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTHORITIES
     *
     * @mbggenerated
     */
    SysAuthorities selectByPrimaryKey(String privilige);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTHORITIES
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAuthorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTHORITIES
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAuthorities record);
}