package com.zhongyang.java.dao;

import java.util.List;

import com.zhongyang.java.pojo.SysFuncList;

public interface SysFuncListMapper {
	
	
	List<SysFuncList> selectAll();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_FUNC_LIST
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_FUNC_LIST
     *
     * @mbggenerated
     */
    int insert(SysFuncList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_FUNC_LIST
     *
     * @mbggenerated
     */
    int insertSelective(SysFuncList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_FUNC_LIST
     *
     * @mbggenerated
     */
    SysFuncList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_FUNC_LIST
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysFuncList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_FUNC_LIST
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysFuncList record);
}